# llm/claude_client.py
import os
import json
import anthropic
from dotenv import load_dotenv

load_dotenv()

CLAUDE_MODEL = "claude-sonnet-4-20250514"
MAX_TOKENS   = 1500


def _get_client() -> anthropic.Anthropic:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError(
            "ANTHROPIC_API_KEY not set. "
            "Add it to .env locally or to Railway environment variables."
        )
    return anthropic.Anthropic(api_key=api_key)


def call_claude(prompt: str) -> dict:
    """Call Claude and return parsed JSON response dict."""
    client = _get_client()
    try:
        message = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=MAX_TOKENS,
            messages=[{"role": "user", "content": prompt}]
        )
        raw = message.content[0].text.strip()

        # Strip markdown fences if Claude adds them despite instructions
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        return json.loads(raw)

    except json.JSONDecodeError as e:
        return _fallback(f"Response parse error: {e}")
    except anthropic.APIError as e:
        return _fallback(f"API error: {e}")
    except Exception as e:
        return _fallback(f"Unexpected error: {e}")


def _fallback(msg: str) -> dict:
    return {
        "answer":               f"Unable to generate a response. {msg}",
        "sources":              [],
        "confidence":           "LOW",
        "confidence_rationale": "System error — response could not be generated.",
        "escalation_required":  True,
        "escalation_reason":    "System error. Please consult a compliance professional directly.",
        "disclaimer":           (
            "This response is generated by an AI system for informational purposes only. "
            "It does not constitute legal or compliance advice."
        ),
    }
